" Plugin management via Vundle
" See https://github.com/VundleVim/Vundle.vim#quick-start
""""""""""""""
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
if isdirectory(expand('~/.vim/bundle/Vundle.vim'))
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'bhurlow/vim-parinfer'
Plugin 'bogado/file-line'
Plugin 'ciaranm/detectindent'
Plugin 'corntrace/bufexplorer'
Plugin 'godlygeek/tabular'
Plugin 'jpalardy/vim-slime'
Plugin 'junegunn/rainbow_parentheses.vim'
Plugin 'mhinz/vim-signify'
Plugin 'micarmst/vim-spellsync'
Plugin 'nathangrigg/vim-beancount'
Plugin 'preservim/nerdcommenter'
Plugin 'preservim/nerdtree'
Plugin 'preservim/tagbar'
Plugin 'rking/ag.vim'
Plugin 'tomtom/tlib_vim'
Plugin 'tpope/vim-abolish'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-sexp-mappings-for-regular-people'
Plugin 'tpope/vim-speeddating'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-vividchalk'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-scripts/VisIncr'
Plugin 'vim-syntastic/syntastic'  " synchronous: blocks on :w
" FIXME Get TabNine working again as I've purchased a license
call vundle#end()
endif
filetype plugin indent on

if has('nvim')
    set termguicolors
endif
set background=dark
colorscheme candy " vividchalk darkbone molokai nord
highlight clear SpellBad
highlight SpellBad term=underline ctermfg=red cterm=underline gui=underline guifg=Red
highlight ColorColumn term=standout ctermbg=magenta guibg=Magenta

if has('unnamedplus')
    set clipboard=unnamedplus
else
    set clipboard=unnamed
endif
set colorcolumn=81  " Touching the column indicates >80 characters
set copyindent
set diffopt+=iwhite,horizontal,context:2
set expandtab
set foldmethod=syntax
set foldlevelstart=99
set formatoptions+=12cnoqr
if has('gui_running')
    set guioptions+=a
    set guioptions-=b
    set guioptions-=l
    set guioptions-=r
endif
set joinspaces
set list
set matchpairs+=<:>
set modeline
set mouse=a
set nobackup
set noerrorbells
set nowrap
set previewheight=10
set scrolljump=-10
set scrolloff=10
set shiftwidth=4
set shortmess+=filmnrxoOtT
set softtabstop=4
set spell
set splitbelow
set splitright
set textwidth=80
set tabstop=4
set title
set undolevels=1000
set viewoptions=folds,cursor,unix,slash
set virtualedit=block
set visualbell
set whichwrap=b,s,h,l,<,>,[,]
set wildignore+=*.aux,*.out,*.toc,.bbl
set wildignore+=*.class
set wildignore+=*.DS_Store
set wildignore+=.hg,.git,.svn,.bzr
set wildignore+=*.luac
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest
set wildignore+=*.pyc
set wildignore+=*.spl
set wildignore+=*.sw?
set wildmode=list:longest
set winminheight=0

" Vim-only: removed in Neovim, or a footgun there
if !has('nvim')
    set lazyredraw
    set ttyfast
    set ttymouse=sgr
endif

" Always reserve the sign column so signify doesn't shift text
" Guarded for old Vim where 'signcolumn' didn't exist yet
if exists('+signcolumn')
    set signcolumn=yes
endif

" Some useful personal macros
noremap =1 /\<\([wW]e\\|[Oo]urs?\\|[Uu]s\\|I\)\>
noremap =4 :set tabstop=4
noremap =8 :set tabstop=8
noremap =b :%s/\s\+$//g
noremap =c :set ft=c
noremap =C :set ft=cpp
noremap =d :set bg=dark
noremap =D :set bg=light
noremap =e :retab
noremap =f !}fmt -w 78 -g 75 -c
noremap == i 
noremap =s !}sort
noremap =u !}sort -u
noremap =v :new $MYVIMRC
noremap =V :source $MYVIMRC

" Toggle folds on space
nnoremap <space> za
vnoremap <space> zf

" Automatically quit if quickfix buffer is last
au BufEnter * call MyLastWindow()
function! MyLastWindow()
    " if the window is quickfix go on
    if &buftype=="quickfix"
        " if this window is last on screen quit without warning
        if winbufnr(2) == -1
            quit!
        endif
    endif
endfunction

" http://thisblog.runsfreesoftware.com/?q=2009/04/20/indent-gnu-style-vim
function! GnuIndent()
    setlocal cinoptions=>4,n-2,{2,^-2,:2,=2,g0,h2,p5,t0,+2,(0,u0,w1,m1
    setlocal shiftwidth=2
    setlocal tabstop=8
endfunction

" Toggle a portrait-monitor-friendly NERDTree and Tagbar setup
" http://unix.stackexchange.com/questions/92942/
function! NERDTreePortrait()
  let w:jumpbacktohere = 1
  " Detect which plugins are open
  if exists('t:NERDTreeBufName')
      let nerdtree_open = bufwinnr(t:NERDTreeBufName) != -1
  else
      let nerdtree_open = 0
  endif
  let tagbar_open = bufwinnr('__Tagbar__') != -1
  " Perform the appropriate action
  if nerdtree_open && tagbar_open
      NERDTreeClose
      TagbarClose
  elseif nerdtree_open
      TagbarOpen
      wincmd J
      wincmd k
      wincmd L
  elseif tagbar_open
      NERDTree
      wincmd J
      wincmd k
      wincmd L
  else
      NERDTree
      TagbarOpen
      wincmd J
      wincmd k
      wincmd L
  endif
  " Jump back to the original window
  for window in range(1, winnr('$'))
      execute window . 'wincmd w'
      if exists('w:jumpbacktohere')
          unlet w:jumpbacktohere
          break
      endif
  endfor
endfunction

" Toggle several useful settings at a few keystrokes
" https://jeffdaly.wordpress.com/2008/05/06/vim-easily-toggle-cursorcolumn-and-cursorline/
" http://vim.wikia.com/wiki/Highlight_current_line
noremap <silent> <Leader>N  :call NERDTreePortrait() <CR>
noremap <silent> <Leader>n  :NERDTreeToggle          <CR>
noremap <silent> <Leader>p  :set paste!              <CR>:set paste?       <CR>
noremap <silent> <Leader>\| :set cursorcolumn!       <CR>:set cursorcolumn?<CR>
noremap <silent> <Leader>-  :set cursorline!         <CR>:set cursorline?  <CR>
noremap <silent> <Leader>#  :set number!             <CR>:set number?      <CR>
noremap <silent> <Leader>S  :set spell!              <CR>:set spell?       <CR>
noremap <silent> <Leader>t  :TagbarToggle            <CR>
noremap <silent> <Leader>w  :set wrap!               <CR>:set wrap?        <CR>

if exists(':SyntasticToggleMode')
    noremap <silent> <Leader>s :SyntasticToggleMode<CR>
endif

" Tabularize mappings from
" http://vimcasts.org/episodes/aligning-text-with-tabular-vim/
if exists(":Tabularize")
  nmap <Leader>a| :Tabularize /|<CR>
  vmap <Leader>a| :Tabularize /|<CR>
  nmap <Leader>a= :Tabularize /=<CR>
  vmap <Leader>a= :Tabularize /=<CR>
  nmap <Leader>a: :Tabularize /:\zs<CR>
  vmap <Leader>a: :Tabularize /:\zs<CR>
  nmap <Leader>a<Space> :Tabularize / \zs<CR>
  vmap <Leader>a<Space> :Tabularize / \zs<CR>
endif

" Miscellaneous plugin settings
autocmd FileType gitcommit set foldmethod=syntax
autocmd BufRead,BufNewFile *.sls set filetype=scheme
let g:signify_vcs_list = [ 'git', 'svn' ]
let g:slime_default_config  = {"sessionname": $STY, "windowname": "0"}
let g:slime_python_ipython = 1
let g:syntastic_auto_jump = 0
let g:syntastic_enable_signs = 1
let g:syntastic_sh_checkers = ['sh', 'shellcheck']
let g:syntastic_cpp_compiler = 'g++'
let g:syntastic_cpp_compiler_options = '-std=c++14'
let g:tex_flavor='latex'
let g:xml_syntax_folding=1

" Avoid seeing common build artifacts in NERDTree
let NERDTreeIgnore=[ '\.a$', 'autom4te.cache', '\.aux$', '\.bbl$', '\.blg$',
                   \ '\.dep$', '\.fdb_latexmk$', '\.fls$', '\.la$', '\.lo$',
                   \ '\.lof$', '\.log$', '\.lot$', '\.o$', '\.out$',
                   \ '\.so$', '\.tdo$', '\.toc$' ]
